name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    # Prevents changesets action from creating a PR on forks
    if: github.repository == 'open-wc/form-participation'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node 20.x
        uses: actions/setup-node@master
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Lint
        run: npm run lint:ci

      - name: Test
        run: npm test

      - name: Version
        run: npm run changeset version

      - name: Publish
        run: npm run changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Prep Commit Back
        # only add modifications (changelog, package.json) and deletions (changeset .md)
        run: |
          git config user.email "you@example.com"
          git config user.name "Open Web Components"
          git add -u
          git commit -m "[skip ci] Automated version bump" --author "Open WC <>"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
